name: Nightly Test run (Jahia Release)

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

jobs:
 integration-tests-rl:
   name: Integration Tests (Jahia RL)
   secrets: inherit
   uses: Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
   with:
     module_id: serverSettings
     jahia_image: jahia/jahia-ee:8
     provisioning_manifest: provisioning-manifest-snapshot.yml
     testrail_project: ServerSettings Module
     artifact_prefix: serset-rl
     timeout_job: 45
