name: Nightly Test run (Jahia Snapshot)

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  integration-tests-sn:
    name: Integration Tests (Jahia SN)
    secrets: inherit
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    with:
      module_id: serverSettings
      jahia_image: ghcr.io/jahia/jahia-ee-dev:8-SNAPSHOT
      provisioning_manifest: provisioning-manifest-snapshot.yml
      testrail_project: ServerSettings Module
      artifact_prefix: serset-sn
      timeout_job: 45